// All 290 Swedish municipalities
export const kommuner = [
  'Ale', 'Alingsås', 'Alvesta', 'Aneby', 'Arboga', 'Arjeplog', 'Arvidsjaur', 'Arvika',
  'Askersund', 'Avesta', 'Bengtsfors', 'Berg', 'Bjurholm', 'Bjuv', 'Boden', 'Bollebygd',
  'Bollnäs', 'Borgholm', 'Borlänge', 'Borås', 'Botkyrka', 'Boxholm', 'Bromölla', 'Bräcke',
  'Burlöv', 'Båstad', 'Dals-Ed', 'Danderyd', 'Degerfors', 'Dorotea', 'Eda', 'Ekerö',
  'Eksjö', 'Emmaboda', 'Enköping', 'Eskilstuna', 'Eslöv', 'Essunga', 'Fagersta', 'Falkenberg',
  'Falköping', 'Falun', 'Filipstad', 'Finspång', 'Flen', 'Forshaga', 'Färgelanda', 'Gagnef',
  'Gislaved', 'Gnesta', 'Gnosjö', 'Gotland', 'Grums', 'Grästorp', 'Gullspång', 'Gävle',
  'Göteborg', 'Götene', 'Habo', 'Hagfors', 'Hallsberg', 'Hallstahammar', 'Halmstad', 'Hammarö',
  'Haninge', 'Haparanda', 'Heby', 'Hedemora', 'Helsingborg', 'Herrljunga', 'Hjo', 'Hofors',
  'Huddinge', 'Hudiksvall', 'Hultsfred', 'Hylte', 'Håbo', 'Hällefors', 'Härjedalen', 'Härnösand',
  'Härryda', 'Hässleholm', 'Höganäs', 'Högsby', 'Hörby', 'Höör', 'Jokkmokk', 'Järfälla',
  'Jönköping', 'Kalix', 'Kalmar', 'Karlsborg', 'Karlshamn', 'Karlskoga', 'Karlskrona', 'Karlstad',
  'Katrineholm', 'Kil', 'Kinda', 'Kiruna', 'Klippan', 'Knivsta', 'Kramfors', 'Kristianstad',
  'Kristinehamn', 'Krokom', 'Kumla', 'Kungsbacka', 'Kungsör', 'Kungälv', 'Kävlinge', 'Köping',
  'Laholm', 'Landskrona', 'Laxå', 'Lekeberg', 'Leksand', 'Lerum', 'Lessebo', 'Lidingö',
  'Lidköping', 'Lilla Edet', 'Lindesberg', 'Linköping', 'Ljungby', 'Ljusdal', 'Ljusnarsberg',
  'Lomma', 'Ludvika', 'Luleå', 'Lund', 'Lycksele', 'Lysekil', 'Malmö', 'Malung-Sälen',
  'Malå', 'Mariestad', 'Mark', 'Markaryd', 'Mellerud', 'Mjölby', 'Mora', 'Motala',
  'Mullsjö', 'Munkedal', 'Munkfors', 'Mölndal', 'Mönsterås', 'Mörbylånga', 'Nacka',
  'Nora', 'Norberg', 'Nordanstig', 'Nordmaling', 'Norrköping', 'Norrtälje', 'Norsjö',
  'Nybro', 'Nykvarn', 'Nyköping', 'Nynäshamn', 'Nässjö', 'Ockelbo', 'Olofström', 'Orsa',
  'Orust', 'Osby', 'Oskarshamn', 'Ovanåker', 'Oxelösund', 'Pajala', 'Partille', 'Perstorp',
  'Piteå', 'Ragunda', 'Robertsfors', 'Ronneby', 'Rättvik', 'Sala', 'Salem', 'Sandviken',
  'Sigtuna', 'Simrishamn', 'Sjöbo', 'Skara', 'Skellefteå', 'Skinnskatteberg', 'Skurup',
  'Skövde', 'Smedjebacken', 'Sollefteå', 'Sollentuna', 'Solna', 'Sorsele', 'Sotenäs',
  'Staffanstorp', 'Stenungsund', 'Stockholm', 'Storfors', 'Storuman', 'Strängnäs',
  'Strömstad', 'Strömsund', 'Sundbyberg', 'Sundsvall', 'Sunne', 'Surahammar', 'Svalöv',
  'Svedala', 'Svenljunga', 'Säffle', 'Säter', 'Sävsjö', 'Söderhamn', 'Söderköping',
  'Södertälje', 'Sölvesborg', 'Tanum', 'Tibro', 'Tidaholm', 'Tierp', 'Timrå', 'Tingsryd',
  'Tjörn', 'Tomelilla', 'Torsby', 'Torsås', 'Tranemo', 'Tranås', 'Trelleborg', 'Trollhättan',
  'Trosa', 'Tyresö', 'Täby', 'Töreboda', 'Uddevalla', 'Ulricehamn', 'Umeå', 'Upplands Väsby',
  'Upplands-Bro', 'Uppsala', 'Uppvidinge', 'Vadstena', 'Vaggeryd', 'Valdemarsvik', 'Vallentuna',
  'Vansbro', 'Vara', 'Varberg', 'Vaxholm', 'Vellinge', 'Vetlanda', 'Vilhelmina', 'Vimmerby',
  'Vindeln', 'Vingåker', 'Vårgårda', 'Vänersborg', 'Vännäs', 'Värmdö', 'Värnamo', 'Västervik',
  'Västerås', 'Växjö', 'Ydre', 'Ystad', 'Åmål', 'Ånge', 'Åre', 'Årjäng', 'Åsele',
  'Åstorp', 'Åtvidaberg', 'Älmhult', 'Älvdalen', 'Älvkarleby', 'Älvsbyn', 'Ängelholm',
  'Öckerö', 'Ödeshög', 'Örebro', 'Örkelljunga', 'Örnsköldsvik', 'Östersund', 'Österåker',
  'Östhammar', 'Östra Göinge', 'Överkalix', 'Övertorneå'
] as const

export type Kommun = typeof kommuner[number]

// Approximate center coordinates for major municipalities (for map display)
// Format: [latitude, longitude]
export const kommunCoordinates: Record<string, [number, number]> = {
  'Stockholm': [59.33, 18.07],
  'Göteborg': [57.71, 11.97],
  'Malmö': [55.60, 13.00],
  'Uppsala': [59.86, 17.64],
  'Linköping': [58.41, 15.63],
  'Västerås': [59.61, 16.55],
  'Örebro': [59.27, 15.21],
  'Norrköping': [58.59, 16.18],
  'Helsingborg': [56.05, 12.69],
  'Jönköping': [57.78, 14.16],
  'Umeå': [63.83, 20.26],
  'Lund': [55.70, 13.19],
  'Borås': [57.72, 12.94],
  'Sundsvall': [62.39, 17.31],
  'Gävle': [60.67, 17.15],
  'Huddinge': [59.24, 17.98],
  'Eskilstuna': [59.37, 16.51],
  'Södertälje': [59.20, 17.63],
  'Karlstad': [59.38, 13.50],
  'Täby': [59.44, 18.07],
  'Växjö': [56.88, 14.81],
  'Halmstad': [56.67, 12.86],
  'Luleå': [65.58, 22.15],
  'Trollhättan': [58.28, 12.29],
  'Östersund': [63.18, 14.64],
  'Botkyrka': [59.24, 17.82],
  'Nacka': [59.31, 18.17],
  'Solna': [59.36, 18.00],
  'Kalmar': [56.66, 16.36],
  'Kristianstad': [56.03, 14.15],
  'Skellefteå': [64.75, 20.95],
  'Falun': [60.61, 15.63],
  'Karlskrona': [56.16, 15.59],
  'Skövde': [58.39, 13.85],
  'Varberg': [57.11, 12.25],
  'Kiruna': [67.86, 20.23],
  'Sollentuna': [59.43, 17.95],
  'Haninge': [59.17, 18.14],
  'Lidingö': [59.37, 18.15],
  'Norrtälje': [59.76, 18.70],
  'Kungsbacka': [57.49, 12.08],
  'Landskrona': [55.87, 12.83],
  'Järfälla': [59.43, 17.83],
  'Nyköping': [58.75, 17.01],
  'Motala': [58.54, 15.04],
  'Piteå': [65.32, 21.48],
  'Värmdö': [59.31, 18.38],
  'Gotland': [57.63, 18.30],
  'Uddevalla': [58.35, 11.94],
  'Trelleborg': [55.38, 13.16],
  'Ängelholm': [56.24, 12.86],
  'Enköping': [59.64, 17.08],
  'Katrineholm': [58.99, 16.21],
  'Härnösand': [62.63, 17.94],
  'Borlänge': [60.48, 15.44],
  'Kumla': [59.13, 15.14],
  'Sandviken': [60.62, 16.78],
  'Sigtuna': [59.62, 17.72],
  'Tyresö': [59.24, 18.23],
  'Lerum': [57.77, 12.27],
  'Kungälv': [57.87, 11.97],
  'Strängnäs': [59.38, 17.03],
  'Ystad': [55.43, 13.82],
  'Mölndal': [57.66, 12.01],
  'Partille': [57.74, 12.11],
}
